### ISSUE TITLE
[BUG]: 启动完成后（运行中）出现错误

### ISSUE THREAD

**Issue by ZoruaFox** [Teahouse-Studios/akari-bot#1079]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法。

### 聊天平台

开发者控制台

### 用户 ID

非本issue必需

### 群组 ID

非本issue必需

### 错误信息

```python
ERROR:apscheduler.executors.default:Job "_ (trigger: date[2024-01-11 22:41:53 CST], next run at: 2024-01-11 22:41:53 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\akari-bot-3uC3wRUU-py3.11\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\akari-bot-dev\akari-bot\modules\secret\__init__.py", line 25, in _
    for x in query["query"]["abuselog"]:
             ~~~~~^^^^^^^^^
KeyError: 'query'
```

### 错误描述

启动小可后出现报错。

### 复现方法

启动小可后出现报错。

### 本应发生的结果

无异常

### 截图

![image](https://github.com/Teahouse-Studios/akari-bot/assets/96456728/3f9e1241-343d-4a82-afe8-d3ffb8ed1e21)

**Comment by OasisAkari** [comment]
minecraft wiki于近期更改了滥用过滤器的权限 建议在配置文件中禁用secret模块文件夹下的内容

**Comment by OasisAkari** [comment]
secret部分内容将于近期更改为需要配置手动启用
