### ISSUE TITLE
[HELP]：`WebSocket API call timeout.`

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#1088]
请注意：这似乎并不是一个 bug。

![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/c53351a8-edea-4c71-bd7d-5e8186ce339c)

自从将 QQ 平台机器人从 go-cqhttp 更换至 OpenShamrock 之后，这种情况就频繁出现，似乎是 Shamrock 或者配置出了问题。

以下是后台报错代码（似乎没啥用）：

```
[Aiocqhttp][core.parser.message:parser:359][2024-01-23 21:25:19][ERROR]:Traceback (most recent call last):
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiocqhttp\api_impl.py", line 104, in fetch
    return await asyncio.wait_for(future, timeout_sec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bots\akari-bot\core\parser\message.py", line 316, in parser
    await execute_submodule(msg, command_first_word, command_split)
  File "D:\bots\akari-bot\core\parser\message.py", line 289, in execute_submodule
    async with msg.Typing(msg):
  File "D:\bots\akari-bot\bots\aiocqhttp\message.py", line 280, in __aenter__
    await bot.send_group_msg(group_id=self.msg.session.target,
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiocqhttp\__init__.py", line 236, in call_action
    return await self._api.call_action(action=action, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiocqhttp\api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiocqhttp\api_impl.py", line 153, in call_action
    return _handle_api_result(await
                              ^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiocqhttp\api_impl.py", line 108, in fetch
    raise NetworkError('WebSocket API call timeout')
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout
```

这是 OpenShamrock 在“WebSocket API call timeout”时的报错：

```
[21:24:16] ERROR moe.fuqiuluo.shamrock.helper.ParamsException: Lack of param type
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

这是有可能起到帮助的部分配置：

akari-bot：

```
qq_host = "0.0.0.0:25565"
```

OpenShamrock：

![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/5a7fb0b6-a01f-4cba-842f-9d0053019111)
![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/39715a83-1b75-4aaf-9295-67b876c9ab36)

其他：

![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/85f3a41e-7b0a-454e-b5d0-cfa1b682406d)
![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/d1414d3c-5ad8-4655-9cf3-b6148190e77a)

**Comment by SilianZ** [comment]
根据 https://github.com/whitechi73/OpenShamrock/issues/217，报错出现的原因可能是 OpenShamrock 的戳一戳使用的是 `touch`作为 key，而 `poke` 是 gocq 的戳一戳 key，传递`poke` 消息需要参数 type，故出现这个报错。

**Comment by SilianZ** [comment]
![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/93fd3ded-95bd-4d75-a97a-e2c04eb99895)

**Comment by SilianZ** [comment]
![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/549b86f2-67d1-4e71-a089-45f5719b936b)
![44e44e35e96c57b29505904d604713b9_720](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/4078b5e0-096f-4933-b81f-117f26ec0497)

**Comment by SilianZ** [comment]
![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/ad06511b-3abd-48a8-b8e4-f97631971b8c)
![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/e2203913-b1d8-41f9-902f-b22a3057980f)
这个功能似乎是针对每个用户的，而不是针对群组的，那为什么还要管理员权限呢🤔。

**Comment by DoroWolf** [comment]
已解决问题，原因：shamrock的戳一戳CQ码与aiocqhttp不同
