### ISSUE TITLE
[BUG]: idk what happened

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#1231]
```
[Aiocqhttp][core.parser.message:parser:223][2024-07-16 01:23:36][INFO]:[QQ|1984841068 (QQ|Group|226330054)] -> [Bot]: ~say 1
[Aiocqhttp][core.parser.message:parser:223][2024-07-16 01:23:47][INFO]:[QQ|1984841068 (QQ|Group|226330054)] -> [Bot]: ~echo 1
[Aiocqhttp][bots.aiocqhttp.message:send_message:115][2024-07-16 01:23:47][INFO]:[Bot] -> [QQ|Group|226330054]: [Plain(text="当前有命令正在执行，请稍后再试。")]
[Aiocqhttp][core.parser.message:parser:447][2024-07-16 01:24:36][ERROR]:Traceback (most recent call last):
  File "C:\Users\silia\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\silia\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiocqhttp\api_impl.py", line 104, in fetch
    return await asyncio.wait_for(future, timeout_sec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "C:\Users\silia\AppData\Local\Programs\Python\Python312\Lib\asyncio\timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bots\akari-bot\core\parser\message.py", line 271, in parser
    await check_target_cooldown(msg)
  File "D:\bots\akari-bot\core\parser\message.py", line 102, in check_target_cooldown
    if await msg.check_native_permission() or await msg.check_permission() or msg.check_super_user():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bots\akari-bot\bots\aiocqhttp\message.py", line 154, in check_native_permission
    get_member_info = await bot.call_action('get_group_member_info', group_id=self.session.target,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiocqhttp\__init__.py", line 236, in call_action
    return await self._api.call_action(action=action, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiocqhttp\api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiocqhttp\api_impl.py", line 153, in call_action
    return _handle_api_result(await
                              ^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiocqhttp\api_impl.py", line 108, in fetch
    raise NetworkError('WebSocket API call timeout')
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout

[Aiocqhttp][bots.aiocqhttp.message:send_message:115][2024-07-16 01:24:36][INFO]:[Bot] -> [QQ|Group|226330054]: [Plain(text="执行命令时发生错误：
WebSocket API call timeout
此问题可能因机器人未及时处理消息导致，若反复发生，请将此消息报告给机器人开发者。
错误汇报地址：https://bugs.bugungu.top/")]
```

**Comment by SilianZ** [comment]
使用 OpenShamrock

**Comment by SilianZ** [comment]
该问题已在 https://github.com/whitechi73/OpenShamrock/issues/334 中提及。
