### ISSUE TITLE
[BUG]: mcmod模块出现问题

### ISSUE THREAD

**Issue by cloudw233** [Teahouse-Studios/akari-bot#405]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

QQ群

### 用户ID

自建的小可bot

### 群组ID

自建的小可bot

### 错误信息

发生错误：执行命令时发生错误，请报告机器人开发者：
Attempt of requesting private IP addresses is not allowed, requesting None.
错误汇报地址： 
https://github.com/Teahouse-Studios/bot/issues/new?assignees=OasisAkari&labels=bug&template=report_bug.yaml&title=%5BBUG%5D%3A+

### 错误描述

执行"~mcmod 核电工艺"出现问题

### 复现方法

1. 执行"~mcmod 核电工艺"
2. 报错

### 本应发生的结果

返回mcmod上的搜索结果

### 截图

[Aiocqhttp][core.parser.message:parser:309][2023-01-16 11:53:03][ERROR]:Traceback (most recent call last):
  File "C:\Users\name\Documents\akari-bot\core\parser\message.py", line 272, in parser
    await execute_submodule(msg, command_first_word, command_split)
  File "C:\Users\name\Documents\akari-bot\core\parser\message.py", line 250, in execute_submodule
    await parsed_msg[0].function(msg)  # 将msg传入下游模块
  File "C:\Users\name\Documents\akari-bot\modules\mcmod\__init__.py", line 15, in main
    message = await m(msg.parsed_msg['<mod_name>'])
  File "C:\Users\name\Documents\akari-bot\modules\mcmod\mcmod.py", line 21, in mcmod
    html = await get_url(search_url, 200)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\name\Documents\akari-bot\core\utils\http.py", line 48, in get_url
    private_ip_check(url)
  File "C:\Users\name\Documents\akari-bot\core\utils\http.py", line 29, in private_ip_check
    raise ValueError(
ValueError: Attempt of requesting private IP addresses is not allowed, requesting None.

**Comment by OasisAkari** [comment]
config.cfg里面设置allow_request_private_ip = True

**Comment by cloudw233** [comment]
> config.cfg里面设置allow_request_private_ip = True

短链接解析到了never gonna give u up
![图片](https://user-images.githubusercontent.com/86039582/212597867-2008f007-3b50-49b1-be02-d99d213ab0b7.png)

**Comment by OasisAkari** [comment]
> > config.cfg里面设置allow_request_private_ip = True
> 
> 短链接解析到了never gonna give u up
> ![图片](https://user-images.githubusercontent.com/86039582/212597867-2008f007-3b50-49b1-be02-d99d213ab0b7.png)
> 

？
可能是触发了什么敏感词，可以不配置内容安全服务再看看

**Comment by OasisAkari** [comment]
好像也不对 我等会检查一下

**Comment by OasisAkari** [comment]
看看log有没有warn级别的输出，有可能是机器人发送的消息出现了你的配置中的文本导致被拦

**Comment by cloudw233** [comment]
未配置内容安全服务
不知道到底发生了什么（

**Comment by cloudw233** [comment]
发现了一条warn级别的输出

**Comment by OasisAkari** [comment]
> 

web_render字段填错了
应该为 `web_render = http://127.0.0.1:19198/`
