### ISSUE TITLE
报错信息求助

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#492]
```python
[Aiocqhttp][core.utils.bot:load_secret:81][2023-03-13 22:36:34][ERROR]:Traceback (most recent call last):
  File "C:\Users\silia\OneDrive\minecraft\akari-bot-4.0.10-release.1\akari-bot-4.0.10-release.1\core\utils\http.py", line 58, in get_
    async with session.get(url, timeout=aiohttp.ClientTimeout(total=timeout), headers=headers) as req:
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 467, in _request
    with timer:
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\silia\OneDrive\minecraft\akari-bot-4.0.10-release.1\akari-bot-4.0.10-release.1\core\utils\bot.py", line 77, in load_secret
    await asyncio.create_task(append_ip())
  File "C:\Users\silia\OneDrive\minecraft\akari-bot-4.0.10-release.1\akari-bot-4.0.10-release.1\core\utils\bot.py", line 71, in append_ip
    ip = await get_url('https://api.ip.sb/geoip', timeout=10, fmt='json')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\OneDrive\minecraft\akari-bot-4.0.10-release.1\akari-bot-4.0.10-release.1\core\utils\http.py", line 78, in get_url
    return await get_()
           ^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\OneDrive\minecraft\akari-bot-4.0.10-release.1\akari-bot-4.0.10-release.1\core\utils\http.py", line 76, in get_
    raise NoReportException(f'请求API超时。')
core.exceptions.NoReportException: 请求API超时。
```

**Comment by OasisAkari** [comment]
这是一个请求自身ip地址的api，如果请求超时建议等一段时间再看看
不管它应该也没关系
