### ISSUE TITLE
[Help]音乐模块的解决方案

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#570]
问一些比较弱智的问题（本人Python新手）：

我写了一个音乐模块，通过请求[网易云音乐API](https://github.com/Binaryify/NeteaseCloudMusicApi)来获取数据，

该API返回的是json文件的数据，

这是数据的一部分：

```json
{
    "result": {
        "songs": [
            {
                "id": 2034742057,
                "name": "アイドル",
                "artists": [
                    {
                        "id": 33927412,
                        "name": "YOASOBI",
                        "picUrl": null,
                        "alias": [],
                        "albumSize": 0,
                        "picId": 0,
                        "fansGroup": null,
                        "img1v1Url": "https://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "img1v1": 0,
                        "trans": null
                    }
                ],
                "album": {
                    "id": 162749810,
                    "name": "アイドル",
                    "artist": {
                        "id": 0,
                        "name": "",
                        "picUrl": null,
                        "alias": [],
                        "albumSize": 0,
                        "picId": 0,
                        "fansGroup": null,
                        "img1v1Url": "https://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "img1v1": 0,
                        "trans": null
                    },
                    "publishTime": 1681228800000,
                    "size": 1,
                    "copyrightId": 1416336,
                    "status": 1,
                    "transNames": [
                        "偶像"
                    ],
                    "picId": 109951168506561760,
                    "mark": 0
                },
                "duration": 213233,
                "copyrightId": 1416336,
                "status": 0,
                "alias": [
                    "TV动画《【我推的孩子】》片头曲"
                ],
                "rtype": 0,
                "ftype": 0,
                "transNames": [
                    "偶像"
                ],
                "mvid": 14618738,
                "fee": 8,
                "rUrl": null,
                "mark": 537141248
            }
        ]
    }
}
```

为了获得并处理这些数据，我导入了Akari-bot自带的`get_url`函数来获取字符串以及`ujson`库来处理数据，

```python
import ujson as json
from core.utils.http import get_url
```

我的处理部分代码如下：

```python
async def search(msg: Bot.MessageSession):
    api_address = await Config('netease_cloud_music_api')
    if api_address and msg.parsed_msg['<value>']:
        api_address += 'search?keywords=' + msg.parsed_msg['<value>']
        send_msg = msg.locale.t('ncmusic.search_result') + '\n'
        cnt = 1
        for k in result_json['result']['songs']:
            if cnt == 10:
                break
            #歌名（如果有翻译则加上翻译）
            send_msg += str(cnt) + '. ' + k['name']
            if k['transNames']:
                send_msg += msg.locale.t('ncmusic.character.(') + k['transNames'] + 
                            msg.locale.t('ncmusic.character.)')
            #歌手名
            send_msg += ' ' + msg.locale.t('ncmusic.come_from.character') + ' '
                        + k['artists']['name']
            #专辑名（如果有翻译则加上翻译）
            send_msg += ' ' + msg.locale.t('ncmusic.come_from.character') + ' ' + 
                        k['album']['name']
            if k['album']['transNames']:
                send_msg += msg.locale.t('ncmusic.character.(') + k['album']['transNames'] + 
                            msg.locale.t('ncmusic.character.)')
            #歌曲号
            send_msg += msg.locale.t('ncmusic.character.(') + k['id'] + msg.locale.t('ncmusic.character.)')
            send_msg += '\n'
            #计数器
            cnt += 1
        send_msg += '\n' + msg.locale.t('ncmusic.message.delete')
        img_path = await msgchain2image([Plain(send_msg)])
        send = await msg.sendMessage(Image(img_path))
        await msg.sleep(90)
        await send.delete()
        await msg.finish()
    elif msg.parsed_msg['<value>'] == None:
        send_msg = msg.locale.t('ncmusic.message.wrong_grammar')
        send = await msg.sendMessage(send_msg)
        await msg.finish()
    elif api_address == None:
        send_msg = msg.locale.t('ncmusic.message.none_config')
        send = await msg.sendMessage(send_msg)
        await msg.finish()
    else:
        send_msg = msg.locale.t('ncmusic.message.error')
        send = await msg.sendMessage(send_msg)
        await msg.finish()
```

通过循环遍历经`ujson`创建的字典之后，拼接字符串再生成图片，最后发送消息。

但是代码出现了比较多的错误，

报错结果如下：

```
Failed to load modules.netease_cloud_music:
Traceback (most recent call last):
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\core\loader\__init__.py", line 38, in load_modules
    importlib.import_module(modules)
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name&#91;level:&#93;, package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\modules\netease_cloud_music\__init__.py", line 27
    send_msg += msg.locale.t('ncmusic.character.(') + k&#91;'transNames'&#93; +
                                                                        ^
SyntaxError: invalid syntax
```

这可能只是代码中的问题之一，希望能帮忙找出更多错误。

**Comment by OasisAkari** [comment]
![image](https://user-images.githubusercontent.com/31803608/234340070-1c90e225-b653-4673-8872-582ea38e6d9e.png)
换行处要加上反斜杠，代表这是一行代码

![image](https://user-images.githubusercontent.com/31803608/234340254-8e4cd732-85a3-45f5-b931-28e89f282a30.png)

这一段我不知道是什么意思，如果你想通过拼接字符串的形式调用i18n键名可以用f-string或者干脆就分几段加起来

![image](https://user-images.githubusercontent.com/31803608/234340770-049d7f96-87c7-44b9-81d0-1809478437b1.png)

或

![image](https://user-images.githubusercontent.com/31803608/234340880-4feb5c7d-d009-4867-af9a-e9ee1ccae55a.png)
