### ISSUE TITLE
[Help：代码报错]

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#573]
这是 #570 的后继Issue，

```json
{
    "result": {
        "songs": [
            {
                "id": 2034742057,
                "name": "アイドル",
                "artists": [
                    {
                        "id": 33927412,
                        "name": "YOASOBI",
                        "picUrl": null,
                        "alias": [],
                        "albumSize": 0,
                        "picId": 0,
                        "fansGroup": null,
                        "img1v1Url": "https://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "img1v1": 0,
                        "trans": null
                    }
                ],
                "album": {
                    "id": 162749810,
                    "name": "アイドル",
                    "artist": {
                        "id": 0,
                        "name": "",
                        "picUrl": null,
                        "alias": [],
                        "albumSize": 0,
                        "picId": 0,
                        "fansGroup": null,
                        "img1v1Url": "https://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                        "img1v1": 0,
                        "trans": null
                    },
                    "publishTime": 1681228800000,
                    "size": 1,
                    "copyrightId": 1416336,
                    "status": 1,
                    "transNames": [
                        "偶像"
                    ],
                    "picId": 109951168506561760,
                    "mark": 0
                },
                "duration": 213233,
                "copyrightId": 1416336,
                "status": 0,
                "alias": [
                    "TV动画《【我推的孩子】》片头曲"
                ],
                "rtype": 0,
                "ftype": 0,
                "transNames": [
                    "偶像"
                ],
                "mvid": 14618738,
                "fee": 8,
                "rUrl": null,
                "mark": 537141248
            }
        ]
    }
}
```

这是我请求到的json数据的一部分,

```python
from core.builtins import Bot
from core.component import module
from core.utils.http import get_url
from config import Config
from core.utils.image import msgchain2image
from core.builtins import Image, Plain
import ujson as json

netease_cloud_music = module(bind_prefix = 'music', developers = ['bugungu'])

@netease_cloud_music.handle('search <value> {{ncmusic.help_doc.search}}', 
                            required_admin = False, required_superuser = False,
                            available_for = '*')

async def search(msg: Bot.MessageSession):
    api_address = Config('netease_cloud_music_api')
    if api_address and msg.parsed_msg['<value>']:
        api_address += 'search?keywords=' + msg.parsed_msg['<value>']
        result = await get_url(api_address, 200, fmt = 'text', request_private_ip = True,)
        result_json = json.loads(result)
        send_msg = msg.locale.t('ncmusic.search_result') + '\n'
        cnt = 1
        for k in result_json['result']['songs']:
            if cnt == 10:
                break
            #歌名（如果有翻译则加上翻译）
            send_msg += str(cnt) + '. ' + k['name']
            if k['transNames']:
                send_msg += msg.locale.t('ncmusic.character.(') + k['transNames'] + \
                            msg.locale.t('ncmusic.character.)')
            #歌手名
            send_msg += ' ' + msg.locale.t('ncmusic.come_from.character') + ' ' \
                        + k['artists']['name']
            #专辑名（如果有翻译则加上翻译）
            send_msg += ' ' + msg.locale.t('ncmusic.come_from.character') + ' ' + \
                        k['album']['name']
            if k['album']['transNames']:
                send_msg += msg.locale.t('ncmusic.character.(') + k['album']['transNames'] + \
                            msg.locale.t('ncmusic.character.)')
            #歌曲号
            send_msg += msg.locale.t('ncmusic.character.(') + k['id'] + msg.locale.t('ncmusic.character.)')
            send_msg += '\n'
            #计数器
            cnt += 1
        send_msg += '\n' + msg.locale.t('ncmusic.message.delete')
        img_path = await msgchain2image([Plain(send_msg)])
        send = await msg.sendMessage(Image(img_path))
        await msg.sleep(90)
        await send.delete()
        await msg.finish()
    elif msg.parsed_msg['<value>'] == None:
        send_msg = msg.locale.t('ncmusic.message.wrong_grammar')
        send = await msg.sendMessage(send_msg)
        await msg.finish()
    elif api_address == None:
        send_msg = msg.locale.t('ncmusic.message.none_config')
        send = await msg.sendMessage(send_msg)
        await msg.finish()
    else:
        send_msg = msg.locale.t('ncmusic.message.error')
        send = await msg.sendMessage(send_msg)
        await msg.finish()
```

这是我经过上一个Issue后更改的代码，

以下是报错信息：

```powershell
[Aiocqhttp][core.parser.message:parser:303][2023-04-26 22:36:04][ERROR]:Traceback (most recent call last):
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\core\parser\message.py", line 263, in parser
    await execute_submodule(msg, command_first_word, command_split)
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\core\parser\message.py", line 238, in execute_submodule
    await parsed_msg[0].function(msg)  # 将msg传入下游模块
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\modules\netease_cloud_music\__init__.py", line 28, in search
    if k['transNames']:
       ~^^^^^^^^^^^^^^
KeyError: 'transNames'
```

**Comment by OasisAkari** [comment]
k里面没有transNames这个键
