### ISSUE TITLE
[Help:代码报错]总之就是非常屎山

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#580]
代码：

```python
@netease_cloud_music.handle('info <ids> {{ncmusic.help_doc.info}}', 
                            required_admin = False, required_superuser = False,
                            available_for = '*')

async def info(msg: Bot.MessageSession):
    api_address = Config('netease_cloud_music_api')
    if api_address and msg.parsed_msg['<ids>']:
        url = api_address + 'detail?ids=' + msg.parsed_msg['<ids>']
        result = await get_url(url, 200, fmt = 'text', request_private_ip = True)
        result_json = json.loads(result)
        send_msg = []
        for k in result_json['songs']:
            send_msg.append(Image(k['al']['picUrl']))
            send_msg_plain = ''
            #歌名
            send_msg_plain += msg.locale.t('ncmusic.info.name') + k['name'] + \
                              msg.locale.t('ncmusic.character.(') + \
                              str(k['id']) + msg.locale.t('ncmusic.character.)') + '\n'
            #专辑名
            send_msg_plain += msg.locale.t('ncmusic.info.album') + k['al']['name'] + \
                              msg.locale.t('ncmusic.character.(') + str(k['al']['id']) + \
                              msg.locale.t('ncmusic.character.)') + '\n'
            #歌手
            send_msg_plain += msg.locale.t('ncmusic.info.artists')
            time = len(k['ar'])
            for i in range(time):
                if i == time - 1:
                    send_msg_plain += k['ar'][i]['name']
                else:
                    send_msg_plain += k['ar'][i]['name'] + ' & '
            send_msg_plain += '\n'
            #歌曲详情页
            song_page = 'https://music.163.com/#/song?id=' + str(k['id'])
            send_msg_plain += msg.locale.t('ncmusic.info.song_page') + song_page + '\n'
            #歌曲链接
            url = api_address + 'song/url?id=' + str(k['id'])
            song = await get_url(url, 200, fmt = 'text', request_private_ip = True)
            song_url = json.loads(song)
            send_msg_plain += msg.locale.t('ncmusic.info.song_url') + song_url['data'][0]['url'] + '\n'
            send_msg_plain += '\n'
            send_msg.append(Plain(send_msg_plain))
        send_msg.append(Plain('\n' + msg.locale.t('ncmusic.message.delete')))
        send = msg.sendMessage(send_msg)
        send.sleep(90)
        send.delete()
        send.finish()
    elif msg.parsed_msg['<id>'] == None:
        send_msg = msg.locale.t('ncmusic.message.wrong_grammar')
        send = await msg.sendMessage(send_msg)
        await msg.finish()
    elif api_address == None:
        send_msg = msg.locale.t('ncmusic.message.none_config')
        send = await msg.sendMessage(send_msg)
        await msg.finish()
    else:
        send_msg = msg.locale.t('ncmusic.message.error')
        send = await msg.sendMessage(send_msg)
        await msg.finish()
```

这段代码已经导入了所有需要用到的库，所以不会有导库问题。

语言文件：

```json
{
    "ncmusic.help_doc.search":"搜索音乐",
    "ncmusic.help_doc.info":"获取音乐详细信息",
    "ncmusic.come_from.character":"——",
    "ncmusic.character.(":"（",
    "ncmusic.character.)":"）",
    "ncmusic.search_result":"搜索结果：",
    "ncmusic.message.wrong_grammar":"语法错误。\n请输入“~help music”查看帮助。",
    "ncmusic.message.delete":"[该消息将在90秒后撤回]",
    "ncmusic.message.none_config":"尚未绑定API！请检查配置文件。",
    "ncmusic.message.error":"出现错误！请联系管理员解决问题",
    "ncmusic.info.name":"歌名：",
    "ncmusic.info.album":"专辑名：",
    "ncmusic.info.artists":"歌手：",
    "ncmusic.info.song_page":"歌曲详情页：",
    "ncmusic.info.song_url":"歌曲链接："
}
```

报错信息：

```powershell
[Akari-Bot][core.utils.http:get_:70][2023-04-29 19:18:49][ERROR]:b'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /detail</pre>\n</body>\n</html>\n'
[Akari-Bot][core.utils.http:get_:70][2023-04-29 19:18:52][ERROR]:b'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /detail</pre>\n</body>\n</html>\n'
[Akari-Bot][core.utils.http:get_:70][2023-04-29 19:18:55][ERROR]:b'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /detail</pre>\n</body>\n</html>\n'
[Akari-Bot][core.parser.message:parser:303][2023-04-29 19:18:55][ERROR]:Traceback (most recent call last):
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\core\parser\message.py", line 263, in parser
    await execute_submodule(msg, command_first_word, command_split)
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\core\parser\message.py", line 238, in execute_submodule
    await parsed_msg[0].function(msg)  # 将msg传入下游模块
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\modules\netease_cloud_music\__init__.py", line 85, in info
    result = await get_url(url, 200, fmt = 'text', request_private_ip = True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\core\utils\http.py", line 84, in get_url
    return await get_()
           ^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\core\utils\http.py", line 71, in get_
    raise ValueError(
ValueError: 404[Ke:Image,path=https://http.cat/404.jpg]

执行命令时发生错误，请报告机器人开发者：
404
```

另外，这段代码我是在`console.py`中测试的。

**Comment by OasisAkari** [comment]
85行处请求的url有误

**Comment by SilianZ** [comment]
哈？
85行？
![image](https://user-images.githubusercontent.com/113701655/235301110-fa7250e5-19b0-4ed3-a479-34ce6e158d85.png)
