### ISSUE TITLE
[Help: 代码报错]

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#587]
```powershell
[Akari-Bot][core.parser.message:parser:305][2023-05-03 01:53:16][ERROR]:Traceback (most recent call last):
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\core\parser\message.py", line 263, in parser
    await execute_submodule(msg, command_first_word, command_split)
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\core\parser\message.py", line 238, in execute_submodule
    await parsed_msg[0].function(msg)  # 将msg传入下游模块
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\OneDrive\minecraft\akari-bot\modules\cave\__init__.py", line 24, in add
    for m in responce:
TypeError: 'NoneType' object is not iterable
```

```python
from core.component import module
from core.builtins import Bot
from core.utils.http import download_to_cache
from core.builtins import Image, Plain
from core.logger import Logger
import ujson as json
import shutil

cave = module(bind_prefix = 'cave', desc = '{cave.desc}', developers = ['bugungu'])

@cave.handle('add {{cave.help_doc.add}}', required_admin = False, required_superuser = False, 
            available_for = '*')

async def add(msg: Bot.MessageSession):
    filename = './modules/cave/data.json'
    responce_get = await msg.waitNextMessage(msg.locale.t('cave.add.msg'))
    responce = await responce_get.toMessageChain()
    data_len = 0
    with open(filename, 'r') as data:
        data_json = json.loads(data.read())
        data_len = len(data_json)
        data.close()
    write_json = {'sender':'',"content":[]}
    for m in responce:
        if isinstance(m, Image):
            i = await m.get()
            Logger.info('Get Image Path: ' + i)
            image_name = str(data_len) + '_' + str(len(write['content']) + 1)
            image_path = download_to_cache(i, image_name)
            shutil.copy(image_path, './modules/cave/images/')
            write['content'].append({'image':image_name})
        else:
            data.close()
            msg.finish(msg.locale.t('cave.error.image'))
        if isinstance(m, Plain):
            i = await m.__str__()
            write['content'].append({'text':i})
    write_json['sender'] = msg.target.senderName()
    if write_json['content'] == None:
        msg.finish(msg.locale.t('cave.error.no_content'))
    with open(filename, 'r + w') as data:
        data_json = json.loads(data.read())
        data_json.append(write_json)
        data.write(json.dumps(data_json))
        data.close()
    msg.finish(msg.locale.t('cave.add.msg') + ' #' + str(len(data_json)))
```

我的代码可能有点难以理解，都是东拼西凑出来的。

**Comment by Dianliang233** [comment]
你应该用数据库，而不是文件系统读写，更不应该用非异步的数据读写。

**Comment by OasisAkari** [comment]
重新同步一下代码再看看，之前的commit没有涵盖到那个console.py

**Comment by Dianliang233** [comment]
至于你真正的问题是MessageChain不是迭代器，你必须要用获取它的.value来获取真正的元素list

**Comment by Dianliang233** [comment]
以及你似乎想要使用jsonl，即用换行分割每一个json对象，但你每次增加message都直接append，在读取的时候却没有逐行读取，肯定会报错的。虽然你真正应该做的事情是弃用文件系统转用数据库。
