### ISSUE TITLE
[BUG]: 最新的Master分支无法重载模块

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#726]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法。

### 聊天平台

开发者控制台

### 用户 ID

1984841068

### 群组 ID

无

### 错误信息

```
[Aiocqhttp][core.parser.message:parser:124][2023-07-29 23:06:29][INFO]:[QQ|1984841068 (QQ|Group|984895425)] -> [Bot]: ～reload hitokoto
[Aiocqhttp][core.parser.message:parser:354][2023-07-29 23:06:29][ERROR]:Traceback (most recent call last):
  File "C:\minecraft\akari-bot\core\parser\message.py", line 308, in parser
    await execute_submodule(msg, command_first_word, command_split)
  File "C:\minecraft\akari-bot\core\parser\message.py", line 282, in execute_submodule
    await parsed_msg[0].function(**kwargs)  # 将msg传入下游模块
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\minecraft\akari-bot\modules\core\modules.py", line 36, in _
    await config_modules(msg)
  File "C:\minecraft\akari-bot\modules\core\modules.py", line 195, in config_modules
    if module_ in unloaded_list:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

[Aiocqhttp][bots.aiocqhttp.message:sendMessage:80][2023-07-29 23:06:29][INFO]:[Bot] -> [QQ|Group|984895425]: [CQ:reply,id=119717220]执行命令时发生错误，请报告机器人开发者：
argument of type 'NoneType' is not iterable
错误汇报地址：https://s.wd-ljt.com/botreportbug
```

### 错误描述

我在执行 `~reload hitokoto` 时出现了如上错误。

### 复现方法

1. 执行 `~reload hitokoto`
2. 出现报错

### 本应发生的结果

正常重载

### 截图

![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/0cb3c90b-8f97-44a7-933c-c53827c047a3)

**Comment by OasisAkari** [comment]
已修复
