### ISSUE TITLE
[BUG]: API请求超时的错误信息多语言无法正常显示

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#766]
```sh
Traceback (most recent call last):
  File "C:\minecraft\akari-bot\core\utils\http.py", line 67, in get_
    async with session.get(url, timeout=aiohttp.ClientTimeout(total=timeout), headers=headers,
  File "C:\minecraft\akari-bot\venv\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\minecraft\akari-bot\venv\Lib\site-packages\aiohttp\client.py", line 560, in _request
    await resp.start(conn)
  File "C:\minecraft\akari-bot\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 894, in start
    with self._timer:
  File "C:\minecraft\akari-bot\venv\Lib\site-packages\aiohttp\helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\minecraft\akari-bot\modules\mcv_rss\__init__.py", line 138, in mcv_jira_rss
    file = json.loads(await get_url('https://bugs.mojang.com/rest/api/2/project/10400/versions', 200, attempt=1))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\minecraft\akari-bot\core\utils\http.py", line 88, in get_url
    return await get_()
           ^^^^^^^^^^^^
  File "C:\minecraft\akari-bot\venv\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\minecraft\akari-bot\venv\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\minecraft\akari-bot\venv\Lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\minecraft\akari-bot\venv\Lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\silia\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\minecraft\akari-bot\venv\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\minecraft\akari-bot\core\utils\http.py", line 86, in get_
    raise NoReportException('{error.request.api.timeout}')
core.exceptions.NoReportException: {error.request.api.timeout}
```

其中的 `('{error.request.api.timeout}')` 没有正常显示

**Comment by Dianliang233** [comment]
我觉得这应该是wai？

**Comment by SilianZ** [comment]
啥意思？

**Comment by SilianZ** [comment]
> 啥意思？

哦 特性（Work as intended）

**Comment by DoroWolf** [comment]
![IMG_20230818_025311](https://github.com/Teahouse-Studios/akari-bot/assets/61273857/69bdae2e-29b7-49c6-addd-a445615bcc05)
值得一提，在局域网中尝试请求或设置部分Wiki时，弹出的超时错误也没有正确i18n处理

**Comment by DoroWolf** [comment]
解决方案也挺简单的：不i18n就行了(((
